name: Deploy test-todo-3

on:
  push:
    branches: main

concurrency:
  group: 
  cancel-in-progress: true
env:

  IMAGE: test-todo-3
  AWS_REGION: 
  AWS_ROLE_ARN: 

  HUMCTL_VERSION: '0.23.1'
  APP_NAME: test-todo-3


jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-7`" >> $GITHUB_ENV

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: 
          aws-region: 

      - name: login to aws ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: create repo if not existing
        id: create-repo
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: 

      - name: "set CONTAINER_REGISTRY env var"
        run: |
          echo "CONTAINER_REGISTRY=$REGISTRY" >> "$GITHUB_ENV"
        env:
          REGISTRY: NaN

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Run the Maven build phase
        run: mvn package -Dmaven.test.skip=true    

      - run: docker build --platform linux/amd64 . -t $CONTAINER_REGISTRY/$IMAGE:$TAG -f ./src/main/docker/Dockerfile.jvm
      - run: docker push $CONTAINER_REGISTRY/$IMAGE:$TAG

      - uses: humanitec/setup-cli-action@v1
        with:
          version: 

      - name: Inform Humanitec
        run: |-
          humctl create artefact-version \
            --token  \
            --org  \
            -t container \
            -n $CONTAINER_REGISTRY/$IMAGE \
            --version $TAG \
            --ref $GITHUB_REF \
            --commit $GITHUB_SHA

      - name: Deploy using Score
        run: |
          humctl score deploy \
            --token  \
            --org  \
            --app  \
            --env development \
            -f score.yaml \
            --extensions humanitec.score.yaml \
            --workload-source-url "https://github.com//blob//score.yaml" \
            --image $CONTAINER_REGISTRY/$IMAGE:$TAG \
            --message ""

